with objectives as (
    select * from {{ ref('int_objectives') }}
),

combos as (

    -- PAIRES (15 combos)
    select 'Blood + Tower'           as combo, countif(first_blood=1 and first_tower=1)                                as total_equipes, sum(case when first_blood=1 and first_tower=1 then win else 0 end)                                as equipes_victorieuses, round(avg(case when first_blood=1 and first_tower=1 then win end)*100,1)           as winrate_pct from objectives union all
    select 'Blood + Dragon'          as combo, countif(first_blood=1 and first_dragon=1)                               as total_equipes, sum(case when first_blood=1 and first_dragon=1 then win else 0 end)                               as equipes_victorieuses, round(avg(case when first_blood=1 and first_dragon=1 then win end)*100,1)          as winrate_pct from objectives union all
    select 'Blood + Baron'           as combo, countif(first_blood=1 and first_baron=1)                                as total_equipes, sum(case when first_blood=1 and first_baron=1 then win else 0 end)                                as equipes_victorieuses, round(avg(case when first_blood=1 and first_baron=1 then win end)*100,1)           as winrate_pct from objectives union all
    select 'Blood + Inhib'           as combo, countif(first_blood=1 and first_inhib=1)                                as total_equipes, sum(case when first_blood=1 and first_inhib=1 then win else 0 end)                                as equipes_victorieuses, round(avg(case when first_blood=1 and first_inhib=1 then win end)*100,1)           as winrate_pct from objectives union all
    select 'Blood + Herald'          as combo, countif(first_blood=1 and first_herald=1)                               as total_equipes, sum(case when first_blood=1 and first_herald=1 then win else 0 end)                               as equipes_victorieuses, round(avg(case when first_blood=1 and first_herald=1 then win end)*100,1)          as winrate_pct from objectives union all
    select 'Tower + Dragon'          as combo, countif(first_tower=1 and first_dragon=1)                               as total_equipes, sum(case when first_tower=1 and first_dragon=1 then win else 0 end)                               as equipes_victorieuses, round(avg(case when first_tower=1 and first_dragon=1 then win end)*100,1)          as winrate_pct from objectives union all
    select 'Tower + Baron'           as combo, countif(first_tower=1 and first_baron=1)                                as total_equipes, sum(case when first_tower=1 and first_baron=1 then win else 0 end)                                as equipes_victorieuses, round(avg(case when first_tower=1 and first_baron=1 then win end)*100,1)           as winrate_pct from objectives union all
    select 'Tower + Inhib'           as combo, countif(first_tower=1 and first_inhib=1)                                as total_equipes, sum(case when first_tower=1 and first_inhib=1 then win else 0 end)                                as equipes_victorieuses, round(avg(case when first_tower=1 and first_inhib=1 then win end)*100,1)           as winrate_pct from objectives union all
    select 'Tower + Herald'          as combo, countif(first_tower=1 and first_herald=1)                               as total_equipes, sum(case when first_tower=1 and first_herald=1 then win else 0 end)                               as equipes_victorieuses, round(avg(case when first_tower=1 and first_herald=1 then win end)*100,1)          as winrate_pct from objectives union all
    select 'Dragon + Baron'          as combo, countif(first_dragon=1 and first_baron=1)                               as total_equipes, sum(case when first_dragon=1 and first_baron=1 then win else 0 end)                               as equipes_victorieuses, round(avg(case when first_dragon=1 and first_baron=1 then win end)*100,1)          as winrate_pct from objectives union all
    select 'Dragon + Inhib'          as combo, countif(first_dragon=1 and first_inhib=1)                               as total_equipes, sum(case when first_dragon=1 and first_inhib=1 then win else 0 end)                               as equipes_victorieuses, round(avg(case when first_dragon=1 and first_inhib=1 then win end)*100,1)          as winrate_pct from objectives union all
    select 'Dragon + Herald'         as combo, countif(first_dragon=1 and first_herald=1)                              as total_equipes, sum(case when first_dragon=1 and first_herald=1 then win else 0 end)                              as equipes_victorieuses, round(avg(case when first_dragon=1 and first_herald=1 then win end)*100,1)         as winrate_pct from objectives union all
    select 'Baron + Inhib'           as combo, countif(first_baron=1 and first_inhib=1)                                as total_equipes, sum(case when first_baron=1 and first_inhib=1 then win else 0 end)                                as equipes_victorieuses, round(avg(case when first_baron=1 and first_inhib=1 then win end)*100,1)           as winrate_pct from objectives union all
    select 'Baron + Herald'          as combo, countif(first_baron=1 and first_herald=1)                               as total_equipes, sum(case when first_baron=1 and first_herald=1 then win else 0 end)                               as equipes_victorieuses, round(avg(case when first_baron=1 and first_herald=1 then win end)*100,1)          as winrate_pct from objectives union all
    select 'Inhib + Herald'          as combo, countif(first_inhib=1 and first_herald=1)                               as total_equipes, sum(case when first_inhib=1 and first_herald=1 then win else 0 end)                               as equipes_victorieuses, round(avg(case when first_inhib=1 and first_herald=1 then win end)*100,1)          as winrate_pct from objectives union all

    -- TRIPLETTES (20 combos)
    select 'Blood + Tower + Dragon'  as combo, countif(first_blood=1 and first_tower=1 and first_dragon=1)             as total_equipes, sum(case when first_blood=1 and first_tower=1 and first_dragon=1 then win else 0 end)             as equipes_victorieuses, round(avg(case when first_blood=1 and first_tower=1 and first_dragon=1 then win end)*100,1)  as winrate_pct from objectives union all
    select 'Blood + Tower + Baron'   as combo, countif(first_blood=1 and first_tower=1 and first_baron=1)              as total_equipes, sum(case when first_blood=1 and first_tower=1 and first_baron=1 then win else 0 end)              as equipes_victorieuses, round(avg(case when first_blood=1 and first_tower=1 and first_baron=1 then win end)*100,1)   as winrate_pct from objectives union all
    select 'Blood + Tower + Inhib'   as combo, countif(first_blood=1 and first_tower=1 and first_inhib=1)              as total_equipes, sum(case when first_blood=1 and first_tower=1 and first_inhib=1 then win else 0 end)              as equipes_victorieuses, round(avg(case when first_blood=1 and first_tower=1 and first_inhib=1 then win end)*100,1)   as winrate_pct from objectives union all
    select 'Blood + Tower + Herald'  as combo, countif(first_blood=1 and first_tower=1 and first_herald=1)             as total_equipes, sum(case when first_blood=1 and first_tower=1 and first_herald=1 then win else 0 end)             as equipes_victorieuses, round(avg(case when first_blood=1 and first_tower=1 and first_herald=1 then win end)*100,1)  as winrate_pct from objectives union all
    select 'Blood + Dragon + Baron'  as combo, countif(first_blood=1 and first_dragon=1 and first_baron=1)             as total_equipes, sum(case when first_blood=1 and first_dragon=1 and first_baron=1 then win else 0 end)             as equipes_victorieuses, round(avg(case when first_blood=1 and first_dragon=1 and first_baron=1 then win end)*100,1)  as winrate_pct from objectives union all
    select 'Blood + Dragon + Inhib'  as combo, countif(first_blood=1 and first_dragon=1 and first_inhib=1)             as total_equipes, sum(case when first_blood=1 and first_dragon=1 and first_inhib=1 then win else 0 end)             as equipes_victorieuses, round(avg(case when first_blood=1 and first_dragon=1 and first_inhib=1 then win end)*100,1)  as winrate_pct from objectives union all
    select 'Blood + Dragon + Herald' as combo, countif(first_blood=1 and first_dragon=1 and first_herald=1)            as total_equipes, sum(case when first_blood=1 and first_dragon=1 and first_herald=1 then win else 0 end)            as equipes_victorieuses, round(avg(case when first_blood=1 and first_dragon=1 and first_herald=1 then win end)*100,1) as winrate_pct from objectives union all
    select 'Blood + Baron + Inhib'   as combo, countif(first_blood=1 and first_baron=1 and first_inhib=1)              as total_equipes, sum(case when first_blood=1 and first_baron=1 and first_inhib=1 then win else 0 end)              as equipes_victorieuses, round(avg(case when first_blood=1 and first_baron=1 and first_inhib=1 then win end)*100,1)   as winrate_pct from objectives union all
    select 'Blood + Baron + Herald'  as combo, countif(first_blood=1 and first_baron=1 and first_herald=1)             as total_equipes, sum(case when first_blood=1 and first_baron=1 and first_herald=1 then win else 0 end)             as equipes_victorieuses, round(avg(case when first_blood=1 and first_baron=1 and first_herald=1 then win end)*100,1)  as winrate_pct from objectives union all
    select 'Blood + Inhib + Herald'  as combo, countif(first_blood=1 and first_inhib=1 and first_herald=1)             as total_equipes, sum(case when first_blood=1 and first_inhib=1 and first_herald=1 then win else 0 end)             as equipes_victorieuses, round(avg(case when first_blood=1 and first_inhib=1 and first_herald=1 then win end)*100,1)  as winrate_pct from objectives union all
    select 'Tower + Dragon + Baron'  as combo, countif(first_tower=1 and first_dragon=1 and first_baron=1)             as total_equipes, sum(case when first_tower=1 and first_dragon=1 and first_baron=1 then win else 0 end)             as equipes_victorieuses, round(avg(case when first_tower=1 and first_dragon=1 and first_baron=1 then win end)*100,1)  as winrate_pct from objectives union all
    select 'Tower + Dragon + Inhib'  as combo, countif(first_tower=1 and first_dragon=1 and first_inhib=1)             as total_equipes, sum(case when first_tower=1 and first_dragon=1 and first_inhib=1 then win else 0 end)             as equipes_victorieuses, round(avg(case when first_tower=1 and first_dragon=1 and first_inhib=1 then win end)*100,1)  as winrate_pct from objectives union all
    select 'Tower + Dragon + Herald' as combo, countif(first_tower=1 and first_dragon=1 and first_herald=1)            as total_equipes, sum(case when first_tower=1 and first_dragon=1 and first_herald=1 then win else 0 end)            as equipes_victorieuses, round(avg(case when first_tower=1 and first_dragon=1 and first_herald=1 then win end)*100,1) as winrate_pct from objectives union all
    select 'Tower + Baron + Inhib'   as combo, countif(first_tower=1 and first_baron=1 and first_inhib=1)              as total_equipes, sum(case when first_tower=1 and first_baron=1 and first_inhib=1 then win else 0 end)              as equipes_victorieuses, round(avg(case when first_tower=1 and first_baron=1 and first_inhib=1 then win end)*100,1)   as winrate_pct from objectives union all
    select 'Tower + Baron + Herald'  as combo, countif(first_tower=1 and first_baron=1 and first_herald=1)             as total_equipes, sum(case when first_tower=1 and first_baron=1 and first_herald=1 then win else 0 end)             as equipes_victorieuses, round(avg(case when first_tower=1 and first_baron=1 and first_herald=1 then win end)*100,1)  as winrate_pct from objectives union all
    select 'Tower + Inhib + Herald'  as combo, countif(first_tower=1 and first_inhib=1 and first_herald=1)             as total_equipes, sum(case when first_tower=1 and first_inhib=1 and first_herald=1 then win else 0 end)             as equipes_victorieuses, round(avg(case when first_tower=1 and first_inhib=1 and first_herald=1 then win end)*100,1)  as winrate_pct from objectives union all
    select 'Dragon + Baron + Inhib'  as combo, countif(first_dragon=1 and first_baron=1 and first_inhib=1)             as total_equipes, sum(case when first_dragon=1 and first_baron=1 and first_inhib=1 then win else 0 end)             as equipes_victorieuses, round(avg(case when first_dragon=1 and first_baron=1 and first_inhib=1 then win end)*100,1)  as winrate_pct from objectives union all
    select 'Dragon + Baron + Herald' as combo, countif(first_dragon=1 and first_baron=1 and first_herald=1)            as total_equipes, sum(case when first_dragon=1 and first_baron=1 and first_herald=1 then win else 0 end)            as equipes_victorieuses, round(avg(case when first_dragon=1 and first_baron=1 and first_herald=1 then win end)*100,1) as winrate_pct from objectives union all
    select 'Dragon + Inhib + Herald' as combo, countif(first_dragon=1 and first_inhib=1 and first_herald=1)            as total_equipes, sum(case when first_dragon=1 and first_inhib=1 and first_herald=1 then win else 0 end)            as equipes_victorieuses, round(avg(case when first_dragon=1 and first_inhib=1 and first_herald=1 then win end)*100,1) as winrate_pct from objectives union all
    select 'Baron + Inhib + Herald'  as combo, countif(first_baron=1 and first_inhib=1 and first_herald=1)             as total_equipes, sum(case when first_baron=1 and first_inhib=1 and first_herald=1 then win else 0 end)             as equipes_victorieuses, round(avg(case when first_baron=1 and first_inhib=1 and first_herald=1 then win end)*100,1)  as winrate_pct from objectives

)

select * from combos
order by winrate_pct desc
limit 10